---

- name: create bash aliases
  template:
    src: bash/00-aliases.sh.j2
    dest: /etc/profile.d/00-aliases.sh
    owner: root
    group: root
    mode: 0644
  when:
    - bash_aliases is defined
