---

- name: create interface directory
  file:
    path: /etc/network/interfaces.d
    state: directory
    mode: '0755'

- name: configure static IP
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: "interfaces/eth0", dest: "/etc/network/interfaces.d/eth0", owner: "root", group: "root", mode: "0644" }
  when: inteerfaces is defined
  notify:
    - reboot host
