---

- name: Add the user {{ odroid_ssh_user }} with a bash shell, appending the group 'admins' to the user's groups
  user:
    name: "{{ odroid_ssh_user }}"
    shell: /bin/bash
    groups: root
    append: yes
    createhome: yes
    password: "{{ odroid_ssh_user_password|password_hash('sha512', odroid_ssh_user_salt) }}"
    update_password: always
    state: present
  when: odroid_ssh_user_password is defined and odroid_ssh_user_salt is defined
